PREFIX lt: <http://ldbcouncil.org/types/>
PREFIX lp: <http://ldbcouncil.org/>

SELECT (COUNT(*) as ?count)
WHERE { 
 ?personA (lp:Person_knows_Person | ^lp:Person_knows_Person ) ?personB .
 ?comment lp:Comment_hasCreator_Person ?personA .
 ?comment lp:Comment_replyOf_Post ?post .
 ?post lp:Post_hasCreator_Person ?personB .
}

