PREFIX lt: <http://ldbcouncil.org/types/>
PREFIX lp: <http://ldbcouncil.org/>

SELECT (COUNT(*) as ?count)
WHERE {
 ?message lp:Message_hasTag_Tag ?tag .
 ?message lp:Message_hasCreator_Person ?person .

 OPTIONAL { ?liker lp:Person_likes_Message ?message }
 OPTIONAL { ?reply lp:Message_replyOf_Message ?message }
}
