PREFIX lt: <http://ldbcouncil.org/types/>
PREFIX lp: <http://ldbcouncil.org/>

SELECT (COUNT(*) as ?count)
WHERE {
 ?message lp:Message_hasTag_Tag ?tag1 .
 ?reply lp:Message_replyOf_Message ?message .
 ?reply lp:Message_hasTag_Tag ?tag2 .
 FILTER( ?tag1 != ?tag2 )
 MINUS {
    ?reply lp:Message_hasTag_Tag ?tag1
 }

}
