PREFIX lt: <http://ldbcouncil.org/types/>
PREFIX lp: <http://ldbcouncil.org/>

SELECT (COUNT(*) as ?count)
WHERE {
 { ?personA lp:Person_knows_Person ?personB . } UNION { ?personB lp:Person_knows_Person ?personA . }
 ?comment lp:Message_hasCreator_Person ?personA .
 ?comment lp:Message_replyOf_Message ?post .
 ?post lp:Message_hasCreator_Person ?personB .
}

