PREFIX lt: <http://ldbcouncil.org/types/>
PREFIX lp: <http://ldbcouncil.org/>

SELECT (COUNT(*) as ?count)
WHERE { 
 ?personA lp:Person_isLocatedIn_City ?cityA .
 ?personB lp:Person_isLocatedIn_City ?cityB .
 ?personC lp:Person_isLocatedIn_City ?cityC .
 ?cityA lp:City_isPartOf_Country ?country .
 ?cityB lp:City_isPartOf_Country ?country .
 ?cityC lp:City_isPartOf_Country ?country .
 
 ?personA (lp:Person_knows_Person | ^lp:Person_knows_Person ) ?personB .
 ?personB (lp:Person_knows_Person | ^lp:Person_knows_Person ) ?personC .
 ?personC (lp:Person_knows_Person | ^lp:Person_knows_Person ) ?personA .
}
