export POSTGRES_HOME=`pwd`/pos/scratch
export POSTGRES_VERSION=15.1
export POSTGRES_SCHEMA_DIR=`pwd`/sql
export POSTGRES_CONTAINER_NAME=lsqb-pos
export POSTGRES_PASSWORD_POLICY="POSTGRES_PASSWORD=mysecretpassword"
export POSTGRES_SHARED_MEMORY=8g
