CREATE TABLE Company (id bigint, isLocatedIn_Country bigint);
CREATE TABLE University (id bigint, isLocatedIn_City bigint);
CREATE TABLE Continent (id bigint);
CREATE TABLE Country (id bigint, isPartOf_Continent bigint);
CREATE TABLE City (id bigint, isPartOf_Country bigint);
CREATE TABLE Tag (id bigint, hasType_TagClass bigint);
CREATE TABLE TagClass (id bigint, isSubclassOf_TagClass bigint);
CREATE TABLE Forum (id bigint, hasModerator_Person bigint);
CREATE TABLE Comment (id bigint, hasCreator_Person bigint, isLocatedIn_Country bigint, replyOf_Post bigint, replyOf_Comment bigint);
CREATE TABLE Post (id bigint, hasCreator_Person bigint, Forum_containerOf bigint, isLocatedIn_Country bigint);
CREATE TABLE Person (id bigint, isLocatedIn_City bigint);
CREATE TABLE Comment_hasTag_Tag (id bigint, hasTag_Tag bigint);
CREATE TABLE Post_hasTag_Tag (id bigint, hasTag_Tag bigint);
CREATE TABLE Forum_hasMember_Person (id bigint, hasMember_Person bigint);
CREATE TABLE Forum_hasTag_Tag (id bigint, hasTag_Tag bigint);
CREATE TABLE Person_hasInterest_Tag (id bigint, hasInterest_Tag bigint);
CREATE TABLE Person_likes_Comment (id bigint, likes_Comment bigint);
CREATE TABLE Person_likes_Post (id bigint, likes_Post bigint);
CREATE TABLE Person_studyAt_University (id bigint, studyAt_University bigint);
CREATE TABLE Person_workAt_Company (id bigint, workAt_Company bigint);
CREATE TABLE Person_knows_Person (Person1id bigint, Person2id bigint);
