COPY university   FROM 'PATHVAR/University.csv'   (DELIMITER '|', HEADER, FORMAT csv);
COPY company      FROM 'PATHVAR/Company.csv'      (DELIMITER '|', HEADER, FORMAT csv);
COPY continent    FROM 'PATHVAR/Continent.csv'    (DELIMITER '|', HEADER, FORMAT csv);
COPY country      FROM 'PATHVAR/Country.csv'      (DELIMITER '|', HEADER, FORMAT csv);
COPY city         FROM 'PATHVAR/City.csv'         (DELIMITER '|', HEADER, FORMAT csv);
COPY tag          FROM 'PATHVAR/Tag.csv'          (DELIMITER '|', HEADER, FORMAT csv);
COPY tagclass     FROM 'PATHVAR/TagClass.csv'     (DELIMITER '|', HEADER, FORMAT csv);
COPY comment      FROM 'PATHVAR/Comment.csv'      (DELIMITER '|', HEADER, FORMAT csv);
COPY forum        FROM 'PATHVAR/Forum.csv'        (DELIMITER '|', HEADER, FORMAT csv);
COPY person       FROM 'PATHVAR/Person.csv'       (DELIMITER '|', HEADER, FORMAT csv);
COPY post         FROM 'PATHVAR/Post.csv'         (DELIMITER '|', HEADER, FORMAT csv);

COPY TagClass_isSubclassOf_TagClass FROM 'PATHVAR/TagClass_isSubclassOf_TagClass.csv' (DELIMITER '|', HEADER, FORMAT csv);
COPY Tag_hasType_TagClass           FROM 'PATHVAR/Tag_hasType_TagClass.csv'           (DELIMITER '|', HEADER, FORMAT csv);
COPY Company_isLocatedIn_Country    FROM 'PATHVAR/Company_isLocatedIn_Country.csv'    (DELIMITER '|', HEADER, FORMAT csv);
COPY University_isLocatedIn_City    FROM 'PATHVAR/University_isLocatedIn_City.csv'    (DELIMITER '|', HEADER, FORMAT csv);
COPY Country_isPartOf_Continent     FROM 'PATHVAR/Country_isPartOf_Continent.csv'     (DELIMITER '|', HEADER, FORMAT csv);
COPY City_isPartOf_Country          FROM 'PATHVAR/City_isPartOf_Country.csv'          (DELIMITER '|', HEADER, FORMAT csv);
COPY Comment_hasCreator_Person      FROM 'PATHVAR/Comment_hasCreator_Person.csv'      (DELIMITER '|', HEADER, FORMAT csv);
COPY Comment_hasTag_Tag             FROM 'PATHVAR/Comment_hasTag_Tag.csv'             (DELIMITER '|', HEADER, FORMAT csv);
COPY Comment_isLocatedIn_Place      FROM 'PATHVAR/Comment_isLocatedIn_Place.csv'      (DELIMITER '|', HEADER, FORMAT csv);
COPY Comment_replyOf_Comment        FROM 'PATHVAR/Comment_replyOf_Comment.csv'        (DELIMITER '|', HEADER, FORMAT csv);
COPY Comment_replyOf_Post           FROM 'PATHVAR/Comment_replyOf_Post.csv'           (DELIMITER '|', HEADER, FORMAT csv);
COPY Forum_containerOf_Post         FROM 'PATHVAR/Forum_containerOf_Post.csv'         (DELIMITER '|', HEADER, FORMAT csv);
COPY Forum_hasMember_Person         FROM 'PATHVAR/Forum_hasMember_Person.csv'         (DELIMITER '|', HEADER, FORMAT csv);
COPY Forum_hasModerator_Person      FROM 'PATHVAR/Forum_hasModerator_Person.csv'      (DELIMITER '|', HEADER, FORMAT csv);
COPY Forum_hasTag_Tag               FROM 'PATHVAR/Forum_hasTag_Tag.csv'               (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_hasInterest_Tag         FROM 'PATHVAR/Person_hasInterest_Tag.csv'         (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_isLocatedIn_Place       FROM 'PATHVAR/Person_isLocatedIn_Place.csv'       (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_likes_Comment           FROM 'PATHVAR/Person_likes_Comment.csv'           (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_likes_Post              FROM 'PATHVAR/Person_likes_Post.csv'              (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_studyAt_University      FROM 'PATHVAR/Person_studyAt_University.csv'      (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_workAt_Company          FROM 'PATHVAR/Person_workAt_Company.csv'          (DELIMITER '|', HEADER, FORMAT csv);
COPY Post_hasCreator_Person         FROM 'PATHVAR/Post_hasCreator_Person.csv'         (DELIMITER '|', HEADER, FORMAT csv);
COPY Post_hasTag_Tag                FROM 'PATHVAR/Post_hasTag_Tag.csv'                (DELIMITER '|', HEADER, FORMAT csv);
COPY Post_isLocatedIn_Place         FROM 'PATHVAR/Post_isLocatedIn_Place.csv'         (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_knows_Person (Person1id, Person2id) FROM 'PATHVAR/Person_knows_Person.csv' (DELIMITER '|', HEADER, FORMAT csv);
COPY Person_knows_Person (Person2id, Person1id) FROM 'PATHVAR/Person_knows_Person.csv' (DELIMITER '|', HEADER, FORMAT csv);
